export const rgisLayers = {
    rgisZouitOKN: {
      title: "Зоны и территории ОКН",
      name: "",
      rgisId: 471,
      styles: [
        {
          id: 0,
          name: "Граница территории ОКН",
          color: "#6F22B6",
          outline: "#90FA86",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 1,
          name: "Зона охраняемого природного ландшафта",
          color: "#A482B3",
          outline: "#F65DF0",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 2,
          name: "Зона регулирования застройки",
          color: "#2470AE",
          outline: "#F629D4",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 3,
          name: "Охранная зона",
          color: "#E5F098",
          outline: "#396947",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 4,
          name: "Защитная зона",
          color: "#8681EE",
          outline: "#A64D5D",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 5,
          name: "Достопримечательное место",
          color: "#2D30C3",
          outline: "#79462F",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 6,
          name: "Не утвержденная граница территории ОКН",
          color: "#DE85C8",
          outline: "#13FD91",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
      ],
    },
    rgisZouitSZZ: {
      title: "Санитарно-защитная зона",
      name: "",
      rgisId: 472,
      styles: [
        {
          id: 0,
          name: "Санитарно-защитная зона",
          color: "#D67077",
          outline: "#8B07E7",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
      ],
    },
    rgisZouitOOPT: {
      title: "Охранная зона ООПТ",
      name: "",
      rgisId: 206,
      styles: [
        {
          id: 0,
          name: "Охранные зоны особо охраняемых природных территорий",
          color: "#A618DD",
          outline: "#EDAFE7",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
      ],
    },
  
    pzzZones: {
      title: "Территориальные зоны ПЗЗ",
      name: "",
      rgisId: 379,
      styles: [
        {
          id: 0,
          name: "Территориальные зоны ПЗЗ",
          color: "#696969",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 120,
          name: "Ж-1 (3100120)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 121,
          name: "Ж-2 (3100121)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 122,
          name: "Ж-3 (3100122)",
          color: "#FBC567",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 123,
          name: "О-1 (3100123)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 124,
          name: "О-2 (3100124)",
          color: "#5D478B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 125,
          name: "О-3 (3100125)",
          color: "#FF99CC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 126,
          name: "О-4",
          color: "#F1CBB4",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 127,
          name: "П (3100127)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 128,
          name: "К (3100128)",
          color: "#936630",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 129,
          name: "И (3100129)",
          color: "#7f734d",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 130,
          name: "Т (3100130)",
          color: "#696969",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 131,
          name: "Р-1 (3100131)",
          color: "#8FCDAC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 132,
          name: "Р-2 (3100132)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 133,
          name: "СП-1 (3100133)",
          color: "#9999FC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 134,
          name: "СП-2 (3100134)",
          color: "#C0C0C0",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 135,
          name: "СП-3 (3100135)",
          color: "#008080",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 136,
          name: "СП-4 (3100136)",
          color: "#00fefe",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 137,
          name: "СХ-1 (3100137)",
          color: "#BAB671",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 138,
          name: "СХ-2 (3100138)",
          color: "#DCFFCE",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 139,
          name: "СХ-3 (3100139)",
          color: "#FAF3BE",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 140,
          name: "СХ-4 (3100140)",
          color: "#B5D664",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 141,
          name: "ИЗ (3100141)",
          color: "#7f734d",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 142,
          name: "КУРТ (3100142)",
          color: "#ffa8eb",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 143,
          name: "Ж-1.1 (3100143)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 144,
          name: "О-1.1 (3100144)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 145,
          name: "О-2б (3100145)",
          color: "#5D478B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 146,
          name: "Р-2.1 (3100146)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 147,
          name: "Ж-1.2 (3100147)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 148,
          name: "Ж-2а (3100148)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 149,
          name: "Ж-2б (3100149)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 150,
          name: "Ж-3а (3100150)",
          color: "#FBC567",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 151,
          name: "ИП (3100151)",
          color: "#7f734d",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 152,
          name: "ТПУ (3100152)",
          color: "#C560E3",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 153,
          name: "Ж-1а (3100153)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 154,
          name: "СХ-3.1 (3100154)",
          color: "#FAF3BE",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 155,
          name: "П-1 (3100155)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 156,
          name: "МФ (3100156)",
          color: "#f9e4f9",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 157,
          name: "Р-3 (3100157)",
          color: "#c9e208",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 158,
          name: "Р-1.1 (3100158)",
          color: "#8FCDAC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 159,
          name: "К-1.1 (3100159)",
          color: "#936630",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 160,
          name: "Ж-2.1 (3100160)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 161,
          name: "СХ-2.1 (3100161)",
          color: "#DCFFCE",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 162,
          name: "СХ-5 (3100162)",
          color: "#9cbb34",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 163,
          name: "ОЭЗ (3100163)",
          color: "#4ea2be",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 164,
          name: "О-1а (3100164)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 165,
          name: "Ц-1 (3100165)",
          color: "#ffa84f",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 166,
          name: "Ц-2 (3100166)",
          color: "#ff70fe",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 167,
          name: "Ц-3 (3100167)",
          color: "#c180ff",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 168,
          name: "МФ-1 (3100168)",
          color: "#f9e4f9",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 169,
          name: "О-5 (3100169)",
          color: "#f1a08d",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 170,
          name: "О-6 (3100170)",
          color: "#f1a08d",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 171,
          name: "Ж-1Б (3100171)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 172,
          name: "Ж-1В (3100172)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 173,
          name: "Ж-1Д (3100173)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 174,
          name: "Ж-1И (3100174)",
          color: "#FF595B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 176,
          name: "Ж-2В (3100176)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 177,
          name: "Ж-2Г (3100177)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 178,
          name: "Ж-2Д (3100178)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 179,
          name: "Ж-2Е (3100179)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 180,
          name: "Ж-2Ж (3100180)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 181,
          name: "Ж-2З (3100181)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 182,
          name: "Ж-2И (3100182)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 183,
          name: "Ж-2К (3100183)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 184,
          name: "Ж-2Л (3100184)",
          color: "#FFF419",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 185,
          name: "К-З (3100185)",
          color: "#936630",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 186,
          name: "К-И (3100186)",
          color: "#936630",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 187,
          name: "К-К (3100187)",
          color: "#936630",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 189,
          name: "О-1А (3100189)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 190,
          name: "О-1Б (3100190)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 191,
          name: "О-1В (3100191)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 192,
          name: "О-1Д (3100192)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 193,
          name: "О-1З (3100193)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 194,
          name: "О-1И (3100194)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 195,
          name: "О-1К (3100195)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 196,
          name: "О-2А (3100196)",
          color: "#5D478B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 197,
          name: "О-2Д (3100197)",
          color: "#5D478B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 198,
          name: "О-2И (3100198)",
          color: "#5D478B",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 199,
          name: "О-3А (3100199)",
          color: "#FF99CC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 200,
          name: "О-3И (3100200)",
          color: "#FF99CC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 201,
          name: "О-3К (3100201)",
          color: "#FF99CC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 202,
          name: "О-4И (3100202)",
          color: "#F1CBB4",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 203,
          name: "О-4Л (3100203)",
          color: "#F1CBB4",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 205,
          name: "П-Б (3100205)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 206,
          name: "П-Д (3100206)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 207,
          name: "П-И (3100207)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 208,
          name: "П-Л (3100208)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 209,
          name: "П-1.1 (3100209)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 210,
          name: "Р-И (3100210)",
          color: "#d4f17a",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 211,
          name: "Р-2.1 (3100211)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 212,
          name: "Р-2Б (3100212)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 213,
          name: "Р-2З (3100213)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 214,
          name: "Р-2И (3100214)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 215,
          name: "Р-2К (3100215)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 216,
          name: "Р-2Л (3100216)",
          color: "#528930",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 217,
          name: "СП-1Л (3100217)",
          color: "#9999FC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 218,
          name: "Т-А (3100218)",
          color: "#696969",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 219,
          name: "Т-И (3100219)",
          color: "#696969",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 220,
          name: "ОП (3100220)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 221,
          name: "МФ-2 (3100221)",
          color: "#f9e4f9",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 222,
          name: "О-1-(т)(р) (3100222)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 223,
          name: "МФ-3 (3100223)",
          color: "#f9e4f9",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 224,
          name: "Р-4 (3100224)",
          color: "#d4f17a",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 225,
          name: "Т-2 (3100225)",
          color: "#696969",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 226,
          name: "Т-3 (3100226)",
          color: "#696969",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 227,
          name: "О-1.2 (3100227)",
          color: "#8B0A50",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 228,
          name: "СП-2а (3100228)",
          color: "#C0C0C0",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 229,
          name: "О-4А (3100229)",
          color: "#F1CBB4",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 230,
          name: "О-4Б (3100230)",
          color: "#F1CBB4",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 231,
          name: "К-1 (3100231)",
          color: "#936630",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 232,
          name: "МФ-4 (3100232)",
          color: "#f9e4f9",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 233,
          name: "О-3.1 (3100233)",
          color: "#FF99CC",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 234,
          name: "СХ-2А (3100234)",
          color: "#DCFFCE",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 235,
          name: "СХ-3А (3100235)",
          color: "#FAF3BE",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 236,
          name: "Па (3100236)",
          color: "#AA9F95",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 237,
          name: "СП-3.1 (3100237)",
          color: "#008080",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 238,
          name: "Р-5 (3100238)",
          color: "#d4f17a",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 239,
          name: "О-4-1 (3100239)",
          color: "#F1CBB4",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 240,
          name: "СХ-5 (3100240)",
          color: "#9cbb34",
          outline: "#2c3136",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
      ],
    },
    rgisZu: {
      title: "Земельные участки",
      name: "",
      rgisId: 403,
      styles: [
        {
          id: 0,
          name: "Объект",
          color: "#C4C4C4",
          outline: "#441D90",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 1,
          name: "Земли водного фонда",
          color: "#99CCFF",
          outline: "#97F05C",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 2,
          name: "Земли запаса",
          color: "#FFCCFF",
          outline: "#3B04E1",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 3,
          name: "Земли лесного фонда",
          color: "#99CC00",
          outline: "#B9056A",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 4,
          name: "Земли населенных пунктов",
          color: "#FF5252",
          outline: "#F70821",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 5,
          name: "Земли особо охраняемых территорий и объектов",
          color: "#FFA7A7",
          outline: "#A3D1F3",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 6,
          name: "Земли промышленности, энергетики, транспорта, связи, радиовещания, телевидения, информатики, земли для обеспечения космической деятельности, земли обороны, безопасности и земли иного специального назначения",
          color: "#C0C0C0",
          outline: "#13D963",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 7,
          name: "Земли сельскохозяйственного назначения",
          color: "#FFFF99",
          outline: "#9BD1EF",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
        {
          id: 8,
          name: "Категория не установлена",
          color: "#C4C4C4",
          outline: "#3EA6C8",
          anchor_x: 0,
          anchor_y: 0,
          type: "POLYGON",
          complex: false,
        },
      ],
    },
  };
  